### ISSUE TITLE
[bug] Inserting a new line with Shift+Enter results in "no glyph" character

### ISSUE THREAD

**Issue by fnune** [gabm/Satty#116]
See:

![Screenshot from 2024-08-26 01-48-10 (edited)](https://github.com/user-attachments/assets/fe244ef8-9d08-4fda-bcb3-eeb63a228a57)

**Comment by fnune** [comment]
Update: looks like this only happens because I'm using a non-default font.

```toml
[font]
family = "Inter"
style = "Regular"
```

I would expect this to work anyway.
