### ISSUE TITLE
[feature] support using env variable in output-filename

### ISSUE THREAD

**Issue by EmmetZ** [gabm/Satty#211]
As the title suggests. For example in config file
```toml
[general]
output-filename = "$HOME/Pictures/test-%Y-%m-%d_%H:%M:%S.png"
```
and Satty should canvert it into `/home/{your username}/Pictures/test-%Y-%m-%d_%H:%M:%S.png`

Is this feature appropriate?

possible solution:
```rust
if output_filename.contains("$") {
    let re = Regex::new(r"\$(\w+)/").unwrap();
    let output = re.replace_all(&output, |caps: &regex::Captures| {
        let var = &caps[1];
        match std::env::var(var) {
            Ok(val) => format!("{}/", val),
            Err(_) => String::new(),
        }
    });
    // println!("output: {}", output);
}
```
